import Navbar from "@/components/Navbar";
import Rightbar from "@/components/Rightbar";
import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-poppins bg-[#0f121b] text-white">
        {children}
        <Toaster />
      </body>
    </html >
  );
}
