import Navbar from "@/components/Navbar";
import Rightbar from "@/components/Rightbar";
import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#0f121b] flex gap-2 text-white">
        <Sidebar />
        <div className="w-full flex flex-col gap-4 p-3">
          <Navbar />
          {/*Change the display to Grid*/}
          <section className="grid grid-cols-[69%,29%] gap-4 w-full">
            {children}
            <Rightbar />
          </section>
        </div>
      </body>
    </html>
  );
}
